### ISSUE TITLE
jmp/jmpz not working correctly

### ISSUE THREAD

**Issue by vgrasso** [EnricoMiccoli/minimass#2]
I tried to use jmp/jmpz instructions in the following code
```
READ 30
READ 31
LOADA 30
STOREA 32
LOADA 31
LDCB 1
DIF
STOREA 31
LOADA 32
LOADB 30
ADD
STOREA 32
LOADA 31
LDCB 1
DIF
STOREA 31
JMPZ 18
JMP 8
WRITE 32
```
But it produced the following output instead of jumping to correct line number
```
> 2
> 2
> 2
> 2
> 2
Bus error: 10
```
Code executed on macOS 10.13

**Comment by EnricoMiccoli** [comment]
The code is missing a HALT instruction on line 19.

**Comment by vgrasso** [comment]
I tried: the presence or absence of HALT at the end of the code makes no difference during execution: same output

**Comment by EnricoMiccoli** [comment]
I have tried on Ubuntu 16.10 and mac os 10.12, I can't reproduce the issue on any of them.
